# Generated by Django 5.2.3 on 2025-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamental',
            name='dividend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
