# Generated by Django 5.2.3 on 2025-06-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_fundamental_dividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamental',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='current_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='debt_to_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='earnings_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='operating_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='price_to_book',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='profit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='return_on_assets',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
