# Generated by Django 5.2.3 on 2025-06-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_fundamental_beta_fundamental_current_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
        migrations.AddField(
            model_name='fundamental',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
