# Generated by Django 5.2.3 on 2025-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_remove_stock_market_cap_fundamental_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamental',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
