# Generated by Django 5.2.3 on 2025-06-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0005_fundamental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamental',
            name='ebit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='ebitda',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
