# Generated by Django 5.2.3 on 2025-06-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0006_fundamental_ebit_fundamental_ebitda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fundamental',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
