# Generated by Django 5.2.3 on 2025-06-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screener', '0007_delete_fundamental_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('exchange', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(db_index=True)),
                ('statement_type', models.CharField(choices=[('IS', 'Income Statement'), ('BS', 'Balance Sheet'), ('CF', 'Cash Flow Statement')], max_length=4)),
                ('field', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'period_end'], name='screener_fu_company_0a9700_idx')],
                'unique_together': {('company', 'period_end', 'statement_type', 'field')},
            },
        ),
    ]
