# Generated by Django 5.2.3 on 2025-06-28 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalsQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(db_index=True)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('period', models.CharField(max_length=4)),
                ('reported_currency', models.CharField(max_length=8)),
                ('cik', models.CharField(max_length=16)),
                ('filing_date', models.DateField()),
                ('accepted_date', models.DateTimeField()),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('cost_of_revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('research_and_development_expenses', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('general_and_administrative_expenses', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('selling_and_marketing_expenses', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('selling_general_and_administrative_expenses', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('other_expenses', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('operating_expenses', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('cost_and_expenses', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('net_interest_income', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('interest_income', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('interest_expense', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('depreciation_and_amortization', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('ebitda', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('ebit', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('non_operating_income_excl_interest', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('operating_income', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('total_other_income_expenses_net', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('income_before_tax', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('income_tax_expense', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('net_income_from_continuing_ops', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('net_income_from_discontinued_ops', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('other_adjustments_to_net_income', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('net_income', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('net_income_deductions', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('bottom_line_net_income', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eps_diluted', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('weighted_average_shs_out', models.BigIntegerField(null=True)),
                ('weighted_average_shs_out_dil', models.BigIntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='screener.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Fundamental',
        ),
        migrations.AddIndex(
            model_name='fundamentalsquarter',
            index=models.Index(fields=['company', 'period_end'], name='screener_fu_company_a7f437_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundamentalsquarter',
            unique_together={('company', 'period_end')},
        ),
    ]
