# Generated by Django 5.2.3 on 2025-06-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0009_fundamentalsquarter_delete_fundamental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentalsquarter',
            name='adj_dividend',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fundamentalsquarter',
            name='declaration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fundamentalsquarter',
            name='dividend',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fundamentalsquarter',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fundamentalsquarter',
            name='record_date',
            field=models.DateField(null=True),
        ),
    ]
