# Generated by Django 5.2.3 on 2025-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0010_fundamentalsquarter_adj_dividend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentalsquarter',
            name='declaration_date',
        ),
        migrations.RemoveField(
            model_name='fundamentalsquarter',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='fundamentalsquarter',
            name='record_date',
        ),
        migrations.AlterField(
            model_name='fundamentalsquarter',
            name='accepted_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fundamentalsquarter',
            name='cik',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='fundamentalsquarter',
            name='filing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fundamentalsquarter',
            name='period_end',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
